/*----- PROTECTED REGION ID(SpecBoardInterfaceClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        SpecBoardInterfaceClass.cpp
//
// description : C++ source for the SpecBoardInterfaceClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the SpecBoardInterface once per process.
//
// project :     Simple PCI FMC Carrier (SPEC) Tango DS interface
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SpecBoardInterfaceClass.h>

/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass.cpp

//-------------------------------------------------------------------
/**
 *	Create SpecBoardInterfaceClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_SpecBoardInterface_class(const char *name) {
		return SpecBoardInterface_ns::SpecBoardInterfaceClass::init(name);
	}
}

namespace SpecBoardInterface_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
SpecBoardInterfaceClass *SpecBoardInterfaceClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		SpecBoardInterfaceClass::SpecBoardInterfaceClass(string &s)
 * description : 	constructor for the SpecBoardInterfaceClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
SpecBoardInterfaceClass::SpecBoardInterfaceClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering SpecBoardInterfaceClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::constructor

	cout2 << "Leaving SpecBoardInterfaceClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		SpecBoardInterfaceClass::~SpecBoardInterfaceClass()
 * description : 	destructor for the SpecBoardInterfaceClass
 */
//--------------------------------------------------------
SpecBoardInterfaceClass::~SpecBoardInterfaceClass()
{
	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		SpecBoardInterfaceClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
SpecBoardInterfaceClass *SpecBoardInterfaceClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new SpecBoardInterfaceClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		SpecBoardInterfaceClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
SpecBoardInterfaceClass *SpecBoardInterfaceClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		ReadRegisterClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadRegisterClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ReadRegisterClass::execute(): arrived" << endl;
	((static_cast<SpecBoardInterface *>(device))->read_register());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ReadRegisterBlockClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadRegisterBlockClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ReadRegisterBlockClass::execute(): arrived" << endl;
	((static_cast<SpecBoardInterface *>(device))->read_register_block());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		WriteRegisterClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *WriteRegisterClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "WriteRegisterClass::execute(): arrived" << endl;
	((static_cast<SpecBoardInterface *>(device))->write_register());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		LoadBitstreamClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *LoadBitstreamClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "LoadBitstreamClass::execute(): arrived" << endl;
	((static_cast<SpecBoardInterface *>(device))->load_bitstream());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum SpecBoardInterfaceClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum SpecBoardInterfaceClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum SpecBoardInterfaceClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void SpecBoardInterfaceClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void SpecBoardInterfaceClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Simple PCI FMC Carrier (SPEC) Tango DS interface");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("The Simple PCIe FMC carrier (SPEC) board is a FPGA based board with SFP connector and PCIe interface (throw the Gennum GN4124 chip bridge). It is under CERN Open Hardware License (CERN OHL v1.2).");
	str_desc.push_back("The SPEC board can hold one FMC card for ADC, DAC, DIO... It can also be used as a standard node for the White Rabbit system.");
	str_desc.push_back("Check the web page http://www.ohwr.org/projects/spec/wiki for full documentation and sources.");
	str_desc.push_back("");
	str_desc.push_back("This class is a simple basic interface for the SPEC board. It allows to:");
	str_desc.push_back("  * load the FPGA bitstream");
	str_desc.push_back("  * read/write registers of the user and gn4124 cores.");
	str_desc.push_back("");
	str_desc.push_back("You will need the libspec library to build and run this class:");
	str_desc.push_back("  * git clone git@ohwr.org:fmc-projects/spec/spec-sw.git");
	str_desc.push_back("  * cd spec-sw/tools");
	str_desc.push_back("  * make");
	str_desc.push_back("  * libspec.a and libspec.so are available");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("SpecBoardInterface");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void SpecBoardInterfaceClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new SpecBoardInterface(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		SpecBoardInterface *dev = static_cast<SpecBoardInterface *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void SpecBoardInterfaceClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::attribute_factory_before
	//	Attribute : barArea
	barAreaAttrib	*bararea = new barAreaAttrib();
	Tango::UserDefaultAttrProp	bararea_prop;
	bararea_prop.set_description("This is the PCIe BAR area on which you want read/write registers.\nBAR0 :FPGA Whishbone bus registers. Access internal FPGA embedded system.\nBAR4 :GN4124 control registers. Access system control as boot mode or loading FPGA bitstream.");
	bararea_prop.set_label("BAR area");
	//	unit	not set for barArea
	//	standard_unit	not set for barArea
	//	display_unit	not set for barArea
	bararea_prop.set_format("%1d");
	bararea_prop.set_max_value("4");
	bararea_prop.set_min_value("0");
	//	max_alarm	not set for barArea
	//	min_alarm	not set for barArea
	//	max_warning	not set for barArea
	//	min_warning	not set for barArea
	//	delta_t	not set for barArea
	//	delta_val	not set for barArea
	
	bararea->set_default_properties(bararea_prop);
	//	Not Polled
	bararea->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(bararea);

	//	Attribute : bitfile
	bitfileAttrib	*bitfile = new bitfileAttrib();
	Tango::UserDefaultAttrProp	bitfile_prop;
	bitfile_prop.set_description("Path of the bitstream to load in the FPGA.");
	bitfile_prop.set_label("Bitstream Path");
	//	unit	not set for bitfile
	//	standard_unit	not set for bitfile
	//	display_unit	not set for bitfile
	//	format	not set for bitfile
	//	max_value	not set for bitfile
	//	min_value	not set for bitfile
	//	max_alarm	not set for bitfile
	//	min_alarm	not set for bitfile
	//	max_warning	not set for bitfile
	//	min_warning	not set for bitfile
	//	delta_t	not set for bitfile
	//	delta_val	not set for bitfile
	
	bitfile->set_default_properties(bitfile_prop);
	//	Not Polled
	bitfile->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(bitfile);

	//	Attribute : readAddress
	readAddressAttrib	*readaddress = new readAddressAttrib();
	Tango::UserDefaultAttrProp	readaddress_prop;
	readaddress_prop.set_description("Address of the register to read");
	readaddress_prop.set_label("Read Address");
	//	unit	not set for readAddress
	//	standard_unit	not set for readAddress
	//	display_unit	not set for readAddress
	readaddress_prop.set_format("%5d");
	//	max_value	not set for readAddress
	//	min_value	not set for readAddress
	//	max_alarm	not set for readAddress
	//	min_alarm	not set for readAddress
	//	max_warning	not set for readAddress
	//	min_warning	not set for readAddress
	//	delta_t	not set for readAddress
	//	delta_val	not set for readAddress
	
	readaddress->set_default_properties(readaddress_prop);
	//	Not Polled
	readaddress->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(readaddress);

	//	Attribute : writeAddress
	writeAddressAttrib	*writeaddress = new writeAddressAttrib();
	Tango::UserDefaultAttrProp	writeaddress_prop;
	writeaddress_prop.set_description("Address of the register to write");
	writeaddress_prop.set_label("Write Address");
	//	unit	not set for writeAddress
	//	standard_unit	not set for writeAddress
	//	display_unit	not set for writeAddress
	writeaddress_prop.set_format("%5d");
	//	max_value	not set for writeAddress
	//	min_value	not set for writeAddress
	//	max_alarm	not set for writeAddress
	//	min_alarm	not set for writeAddress
	//	max_warning	not set for writeAddress
	//	min_warning	not set for writeAddress
	//	delta_t	not set for writeAddress
	//	delta_val	not set for writeAddress
	
	writeaddress->set_default_properties(writeaddress_prop);
	//	Not Polled
	writeaddress->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(writeaddress);

	//	Attribute : readValue
	readValueAttrib	*readvalue = new readValueAttrib();
	Tango::UserDefaultAttrProp	readvalue_prop;
	readvalue_prop.set_description("Value read at readAddress");
	readvalue_prop.set_label("Read Value");
	//	unit	not set for readValue
	//	standard_unit	not set for readValue
	//	display_unit	not set for readValue
	//	format	not set for readValue
	//	max_value	not set for readValue
	//	min_value	not set for readValue
	//	max_alarm	not set for readValue
	//	min_alarm	not set for readValue
	//	max_warning	not set for readValue
	//	min_warning	not set for readValue
	//	delta_t	not set for readValue
	//	delta_val	not set for readValue
	
	readvalue->set_default_properties(readvalue_prop);
	//	Not Polled
	readvalue->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(readvalue);

	//	Attribute : writeValue
	writeValueAttrib	*writevalue = new writeValueAttrib();
	Tango::UserDefaultAttrProp	writevalue_prop;
	writevalue_prop.set_description("Value to write at writeAddress");
	writevalue_prop.set_label("Write Value");
	//	unit	not set for writeValue
	//	standard_unit	not set for writeValue
	//	display_unit	not set for writeValue
	//	format	not set for writeValue
	//	max_value	not set for writeValue
	//	min_value	not set for writeValue
	//	max_alarm	not set for writeValue
	//	min_alarm	not set for writeValue
	//	max_warning	not set for writeValue
	//	min_warning	not set for writeValue
	//	delta_t	not set for writeValue
	//	delta_val	not set for writeValue
	
	writevalue->set_default_properties(writevalue_prop);
	//	Not Polled
	writevalue->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(writevalue);

	//	Attribute : sizeReadBlock
	sizeReadBlockAttrib	*sizereadblock = new sizeReadBlockAttrib();
	Tango::UserDefaultAttrProp	sizereadblock_prop;
	sizereadblock_prop.set_description("Size of the register block to read (number of registers to read).");
	sizereadblock_prop.set_label("Size of Register Block");
	//	unit	not set for sizeReadBlock
	//	standard_unit	not set for sizeReadBlock
	//	display_unit	not set for sizeReadBlock
	//	format	not set for sizeReadBlock
	//	max_value	not set for sizeReadBlock
	//	min_value	not set for sizeReadBlock
	//	max_alarm	not set for sizeReadBlock
	//	min_alarm	not set for sizeReadBlock
	//	max_warning	not set for sizeReadBlock
	//	min_warning	not set for sizeReadBlock
	//	delta_t	not set for sizeReadBlock
	//	delta_val	not set for sizeReadBlock
	
	sizereadblock->set_default_properties(sizereadblock_prop);
	//	Not Polled
	sizereadblock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(sizereadblock);

	//	Attribute : readRegisterBlock
	readRegisterBlockAttrib	*readregisterblock = new readRegisterBlockAttrib();
	Tango::UserDefaultAttrProp	readregisterblock_prop;
	readregisterblock_prop.set_description("This spectrum contains the values of a block of registers.\nThe block starts at address readAddress and reads next registers until sizeReadBlock is reached.");
	readregisterblock_prop.set_label("Register Block");
	//	unit	not set for readRegisterBlock
	//	standard_unit	not set for readRegisterBlock
	//	display_unit	not set for readRegisterBlock
	//	format	not set for readRegisterBlock
	//	max_value	not set for readRegisterBlock
	//	min_value	not set for readRegisterBlock
	//	max_alarm	not set for readRegisterBlock
	//	min_alarm	not set for readRegisterBlock
	//	max_warning	not set for readRegisterBlock
	//	min_warning	not set for readRegisterBlock
	//	delta_t	not set for readRegisterBlock
	//	delta_val	not set for readRegisterBlock
	
	readregisterblock->set_default_properties(readregisterblock_prop);
	//	Not Polled
	readregisterblock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(readregisterblock);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void SpecBoardInterfaceClass::command_factory()
{
	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::command_factory_before


	//	Command ReadRegister
	ReadRegisterClass	*pReadRegisterCmd =
		new ReadRegisterClass("ReadRegister",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pReadRegisterCmd);

	//	Command ReadRegisterBlock
	ReadRegisterBlockClass	*pReadRegisterBlockCmd =
		new ReadRegisterBlockClass("ReadRegisterBlock",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pReadRegisterBlockCmd);

	//	Command WriteRegister
	WriteRegisterClass	*pWriteRegisterCmd =
		new WriteRegisterClass("WriteRegister",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pWriteRegisterCmd);

	//	Command LoadBitstream
	LoadBitstreamClass	*pLoadBitstreamCmd =
		new LoadBitstreamClass("LoadBitstream",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pLoadBitstreamCmd);

	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		SpecBoardInterfaceClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void SpecBoardInterfaceClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		SpecBoardInterfaceClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void SpecBoardInterfaceClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		SpecBoardInterface *dev = static_cast<SpecBoardInterface *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : SpecBoardInterfaceClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *SpecBoardInterfaceClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; it++)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(SpecBoardInterfaceClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	SpecBoardInterfaceClass::Additional Methods
} //	namespace
